[pytest]
; attic/ holds quarantined code that cannot be imported; see attic/README.md
norecursedirs=_old fixme fix* out-* attic docs deps
python_files = test_*.py T*_*.py plot_*.py P*_*.py
python_functions = test_* T_* plot_* P_*
usefixtures = closefigs
filterwarnings = ignore::DeprecationWarning

[pytest-watch]
ignore = .*
ignore_patterns = .*

[pytest-watcher]
ignore_patterns = .*