[pytest]
norecursedirs=_old fixme fix* out-*
python_files = test_*.py T*_*.py plot_*.py P*_*.py
python_functions = test_* T_* plot_* P_*
usefixtures = closefigs
filterwarnings = ignore::DeprecationWarning

[pytest-watch]
ignore = .* 
